# Generated by Django 3.2.21 on 2023-09-17 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_lengkap', models.CharField(max_length=250)),
                ('nama_panggilan', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('umur', models.PositiveSmallIntegerField()),
                ('kelompok', models.SmallIntegerField(choices=[(1, 'SD KELOMPOK 1'), (2, 'SD KELOMPOK 2'), (3, 'SD GELOMBANG 2'), (3, 'SMP - SMA')])),
                ('telp_pribadi', models.IntegerField()),
                ('telp_orangtua', models.IntegerField()),
                ('sekolah', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tgl_latihan', models.DateTimeField()),
                ('materi_latihan', models.TextField()),
                ('kendala', models.TextField(blank=True)),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(to='absensi.Student')),
            ],
        ),
    ]
